/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "mount.h"

bool_t
xdr_FHandle (XDR *xdrs, FHandle objp)
{
	register int32_t *buf;

	 if (!xdr_opaque (xdrs, objp, FHSIZE))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_FHStatus (XDR *xdrs, FHStatus *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case 0:
		 if (!xdr_FHandle (xdrs, objp->FHStatus_u.directory))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_DirPath (XDR *xdrs, DirPath *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->DirPath_val, (u_int *) &objp->DirPath_len, MNTPATHLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Name (XDR *xdrs, Name *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MNTNAMLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_MountList (XDR *xdrs, MountList *objp)
{
	register int32_t *buf;

	 if (!xdr_Name (xdrs, &objp->hostName))
		 return FALSE;
	 if (!xdr_DirPath (xdrs, &objp->directory))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (MountList), (xdrproc_t) xdr_MountList))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_MountListRes (XDR *xdrs, MountListRes *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (MountList), (xdrproc_t) xdr_MountList))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Groups (XDR *xdrs, Groups *objp)
{
	register int32_t *buf;

	 if (!xdr_Name (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (Groups), (xdrproc_t) xdr_Groups))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ExportList (XDR *xdrs, ExportList *objp)
{
	register int32_t *buf;

	 if (!xdr_DirPath (xdrs, &objp->fileSystem))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->groups, sizeof (Groups), (xdrproc_t) xdr_Groups))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (ExportList), (xdrproc_t) xdr_ExportList))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ExportListRes (XDR *xdrs, ExportListRes *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (ExportList), (xdrproc_t) xdr_ExportList))
		 return FALSE;
	return TRUE;
}
