/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "nfs.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

void *
nfsproc_null_2(void *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NFSPROC_NULL,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

AttrStat *
nfsproc_getattr_2(char *argp, CLIENT *clnt)
{
	static AttrStat clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NFSPROC_GETATTR,
		(xdrproc_t) xdr_FHandle, (caddr_t) argp,
		(xdrproc_t) xdr_AttrStat, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

AttrStat *
nfsproc_setattr_2(SAttrArgs *argp, CLIENT *clnt)
{
	static AttrStat clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NFSPROC_SETATTR,
		(xdrproc_t) xdr_SAttrArgs, (caddr_t) argp,
		(xdrproc_t) xdr_AttrStat, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

void *
nfsproc_root_2(void *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NFSPROC_ROOT,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

DirOpRes *
nfsproc_lookup_2(DirOpArgs *argp, CLIENT *clnt)
{
	static DirOpRes clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NFSPROC_LOOKUP,
		(xdrproc_t) xdr_DirOpArgs, (caddr_t) argp,
		(xdrproc_t) xdr_DirOpRes, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

ReadLinkRes *
nfsproc_readlink_2(char *argp, CLIENT *clnt)
{
	static ReadLinkRes clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NFSPROC_READLINK,
		(xdrproc_t) xdr_FHandle, (caddr_t) argp,
		(xdrproc_t) xdr_ReadLinkRes, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

ReadRes *
nfsproc_read_2(ReadArgs *argp, CLIENT *clnt)
{
	static ReadRes clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NFSPROC_READ,
		(xdrproc_t) xdr_ReadArgs, (caddr_t) argp,
		(xdrproc_t) xdr_ReadRes, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

void *
nfsproc_writecache_2(void *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NFSPROC_WRITECACHE,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

AttrStat *
nfsproc_write_2(WriteArgs *argp, CLIENT *clnt)
{
	static AttrStat clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NFSPROC_WRITE,
		(xdrproc_t) xdr_WriteArgs, (caddr_t) argp,
		(xdrproc_t) xdr_AttrStat, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DirOpRes *
nfsproc_create_2(CreateArgs *argp, CLIENT *clnt)
{
	static DirOpRes clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NFSPROC_CREATE,
		(xdrproc_t) xdr_CreateArgs, (caddr_t) argp,
		(xdrproc_t) xdr_DirOpRes, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Stat *
nfsproc_remove_2(DirOpArgs *argp, CLIENT *clnt)
{
	static Stat clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NFSPROC_REMOVE,
		(xdrproc_t) xdr_DirOpArgs, (caddr_t) argp,
		(xdrproc_t) xdr_Stat, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Stat *
nfsproc_rename_2(RenameArgs *argp, CLIENT *clnt)
{
	static Stat clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NFSPROC_RENAME,
		(xdrproc_t) xdr_RenameArgs, (caddr_t) argp,
		(xdrproc_t) xdr_Stat, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Stat *
nfsproc_link_2(LinkArgs *argp, CLIENT *clnt)
{
	static Stat clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NFSPROC_LINK,
		(xdrproc_t) xdr_LinkArgs, (caddr_t) argp,
		(xdrproc_t) xdr_Stat, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Stat *
nfsproc_symlink_2(SymLinkArgs *argp, CLIENT *clnt)
{
	static Stat clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NFSPROC_SYMLINK,
		(xdrproc_t) xdr_SymLinkArgs, (caddr_t) argp,
		(xdrproc_t) xdr_Stat, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

DirOpRes *
nfsproc_mkdir_2(CreateArgs *argp, CLIENT *clnt)
{
	static DirOpRes clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NFSPROC_MKDIR,
		(xdrproc_t) xdr_CreateArgs, (caddr_t) argp,
		(xdrproc_t) xdr_DirOpRes, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Stat *
nfsproc_rmdir_2(DirOpArgs *argp, CLIENT *clnt)
{
	static Stat clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NFSPROC_RMDIR,
		(xdrproc_t) xdr_DirOpArgs, (caddr_t) argp,
		(xdrproc_t) xdr_Stat, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

ReadDirRes *
nfsproc_readdir_2(ReadDirArgs *argp, CLIENT *clnt)
{
	static ReadDirRes clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NFSPROC_READDIR,
		(xdrproc_t) xdr_ReadDirArgs, (caddr_t) argp,
		(xdrproc_t) xdr_ReadDirRes, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

StatFSRes *
nfsproc_statfs_2(char *argp, CLIENT *clnt)
{
	static StatFSRes clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NFSPROC_STATFS,
		(xdrproc_t) xdr_FHandle, (caddr_t) argp,
		(xdrproc_t) xdr_StatFSRes, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
