/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "nfs.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
nfs_program_2(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		FHandle nfsproc_getattr_2_arg;
		SAttrArgs nfsproc_setattr_2_arg;
		DirOpArgs nfsproc_lookup_2_arg;
		FHandle nfsproc_readlink_2_arg;
		ReadArgs nfsproc_read_2_arg;
		WriteArgs nfsproc_write_2_arg;
		CreateArgs nfsproc_create_2_arg;
		DirOpArgs nfsproc_remove_2_arg;
		RenameArgs nfsproc_rename_2_arg;
		LinkArgs nfsproc_link_2_arg;
		SymLinkArgs nfsproc_symlink_2_arg;
		CreateArgs nfsproc_mkdir_2_arg;
		DirOpArgs nfsproc_rmdir_2_arg;
		ReadDirArgs nfsproc_readdir_2_arg;
		FHandle nfsproc_statfs_2_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NFSPROC_NULL:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) nfsproc_null_2_svc;
		break;

	case NFSPROC_GETATTR:
		_xdr_argument = (xdrproc_t) xdr_FHandle;
		_xdr_result = (xdrproc_t) xdr_AttrStat;
		local = (char *(*)(char *, struct svc_req *)) nfsproc_getattr_2_svc;
		break;

	case NFSPROC_SETATTR:
		_xdr_argument = (xdrproc_t) xdr_SAttrArgs;
		_xdr_result = (xdrproc_t) xdr_AttrStat;
		local = (char *(*)(char *, struct svc_req *)) nfsproc_setattr_2_svc;
		break;

	case NFSPROC_ROOT:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) nfsproc_root_2_svc;
		break;

	case NFSPROC_LOOKUP:
		_xdr_argument = (xdrproc_t) xdr_DirOpArgs;
		_xdr_result = (xdrproc_t) xdr_DirOpRes;
		local = (char *(*)(char *, struct svc_req *)) nfsproc_lookup_2_svc;
		break;

	case NFSPROC_READLINK:
		_xdr_argument = (xdrproc_t) xdr_FHandle;
		_xdr_result = (xdrproc_t) xdr_ReadLinkRes;
		local = (char *(*)(char *, struct svc_req *)) nfsproc_readlink_2_svc;
		break;

	case NFSPROC_READ:
		_xdr_argument = (xdrproc_t) xdr_ReadArgs;
		_xdr_result = (xdrproc_t) xdr_ReadRes;
		local = (char *(*)(char *, struct svc_req *)) nfsproc_read_2_svc;
		break;

	case NFSPROC_WRITECACHE:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) nfsproc_writecache_2_svc;
		break;

	case NFSPROC_WRITE:
		_xdr_argument = (xdrproc_t) xdr_WriteArgs;
		_xdr_result = (xdrproc_t) xdr_AttrStat;
		local = (char *(*)(char *, struct svc_req *)) nfsproc_write_2_svc;
		break;

	case NFSPROC_CREATE:
		_xdr_argument = (xdrproc_t) xdr_CreateArgs;
		_xdr_result = (xdrproc_t) xdr_DirOpRes;
		local = (char *(*)(char *, struct svc_req *)) nfsproc_create_2_svc;
		break;

	case NFSPROC_REMOVE:
		_xdr_argument = (xdrproc_t) xdr_DirOpArgs;
		_xdr_result = (xdrproc_t) xdr_Stat;
		local = (char *(*)(char *, struct svc_req *)) nfsproc_remove_2_svc;
		break;

	case NFSPROC_RENAME:
		_xdr_argument = (xdrproc_t) xdr_RenameArgs;
		_xdr_result = (xdrproc_t) xdr_Stat;
		local = (char *(*)(char *, struct svc_req *)) nfsproc_rename_2_svc;
		break;

	case NFSPROC_LINK:
		_xdr_argument = (xdrproc_t) xdr_LinkArgs;
		_xdr_result = (xdrproc_t) xdr_Stat;
		local = (char *(*)(char *, struct svc_req *)) nfsproc_link_2_svc;
		break;

	case NFSPROC_SYMLINK:
		_xdr_argument = (xdrproc_t) xdr_SymLinkArgs;
		_xdr_result = (xdrproc_t) xdr_Stat;
		local = (char *(*)(char *, struct svc_req *)) nfsproc_symlink_2_svc;
		break;

	case NFSPROC_MKDIR:
		_xdr_argument = (xdrproc_t) xdr_CreateArgs;
		_xdr_result = (xdrproc_t) xdr_DirOpRes;
		local = (char *(*)(char *, struct svc_req *)) nfsproc_mkdir_2_svc;
		break;

	case NFSPROC_RMDIR:
		_xdr_argument = (xdrproc_t) xdr_DirOpArgs;
		_xdr_result = (xdrproc_t) xdr_Stat;
		local = (char *(*)(char *, struct svc_req *)) nfsproc_rmdir_2_svc;
		break;

	case NFSPROC_READDIR:
		_xdr_argument = (xdrproc_t) xdr_ReadDirArgs;
		_xdr_result = (xdrproc_t) xdr_ReadDirRes;
		local = (char *(*)(char *, struct svc_req *)) nfsproc_readdir_2_svc;
		break;

	case NFSPROC_STATFS:
		_xdr_argument = (xdrproc_t) xdr_FHandle;
		_xdr_result = (xdrproc_t) xdr_StatFSRes;
		local = (char *(*)(char *, struct svc_req *)) nfsproc_statfs_2_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (NFS_PROGRAM, NFS_VERSION);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, NFS_PROGRAM, NFS_VERSION, nfs_program_2, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (NFS_PROGRAM, NFS_VERSION, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, NFS_PROGRAM, NFS_VERSION, nfs_program_2, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (NFS_PROGRAM, NFS_VERSION, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
